{% set name = "sardana-tango" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/sardana-org/sardana-tango/-/archive/{{ version }}/sardana-tango-{{ version }}.tar.gz
  sha256: 708f5cc74f5bb09cf499f385dfc64b14e98dca45cdcc89f94ea395e703fb6cdd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sardana
    - pytango

test:
  imports:
    - sardana_tango
    - sardana_tango.ctrl.TangoAttrCTCtrl
    - sardana_tango.ctrl.TangoAttrIORCtrl
    - sardana_tango.ctrl.TangoAttrMotorCtrl
    - sardana_tango.ctrl.TangoAttrZeroDCtrl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/sardana-org/sardana-tango
  summary: Sardana Tango plugins
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
